### ISSUE TITLE
broken package?

### ISSUE THREAD

**Issue by sokoow** [alex4321/langchain-openai-limiter#4]
Hey, I am getting this when trying to use this package:

```
# poetry run python ./main.py
Traceback (most recent call last):
  File "/home/crewai/stock_analysis/./main.py", line 4, in <module>
    from stock_analysis_agents import StockAnalysisAgents
  File "/home/crewai/stock_analysis/stock_analysis_agents.py", line 9, in <module>
    from langchain_openai_limiter import LimitAwaitChatOpenAI
  File "/root/.cache/pypoetry/virtualenvs/stock-analysis-crew-jF_CJZer-py3.10/lib/python3.10/site-packages/langchain_openai_limiter/__init__.py", line 6, in <module>
    from .choose_key_chat_openai import ChooseKeyChatOpenAI
  File "/root/.cache/pypoetry/virtualenvs/stock-analysis-crew-jF_CJZer-py3.10/lib/python3.10/site-packages/langchain_openai_limiter/choose_key_chat_openai.py", line 11, in <module>
    from .capture_headers import attach_session_hooks
  File "/root/.cache/pypoetry/virtualenvs/stock-analysis-crew-jF_CJZer-py3.10/lib/python3.10/site-packages/langchain_openai_limiter/capture_headers.py", line 9, in <module>
    import openai.api_requestor
ModuleNotFoundError: No module named 'openai.api_requestor'
```

is it a case of my version of openai, or this package is broken?

**Comment by sokoow** [comment]
OpenAI api package version I have is:

```
$poetry run pip show openai 
Name: openai
Version: 1.7.1
Summary: The official Python library for the openai API
Home-page: 
Author: 
Author-email: OpenAI <support@openai.com>
License: 
Location: /root/.cache/pypoetry/virtualenvs/stock-analysis-crew-jF_CJZer-py3.10/lib/python3.10/site-packages
Requires: anyio, distro, httpx, pydantic, sniffio, tqdm, typing-extensions
Required-by: crewai, langchain-openai, langchain_openai_limiter
```
